language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - echo "Testing..."

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}